import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { FooterComponent } from "./components/ui/footercomponent";
import QueryProvider from "@/providers/QueryProvider";
import { SiteProvider } from "./context/siteContext";
import { ToastProvider } from "./context/ToastContext";
import { ClerkProvider, Show, SignInButton, UserButton } from '@clerk/nextjs'
import 'bootstrap/dist/css/bootstrap.min.css';  // Single line fix!

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pb-40`}
      >
        {/* auth provider covers the entire app */}
        <AuthProvider>
          <SiteProvider>
            <QueryProvider>
              <ToastProvider>
                <ClerkProvider>
                  <header className="flex justify-end items-center p-4 gap-4 h-16 position-fixed top-0 right-0">
                    <Show when="signed-out">
                      <SignInButton />
                    </Show>
                    <Show when="signed-in">
                      <UserButton />
                    </Show>
                  </header>
                  {children}
                </ClerkProvider>
              </ToastProvider>
            </QueryProvider>
          </SiteProvider>
        </AuthProvider>
            <FooterComponent></FooterComponent>
      </body>
    </html>
  );
}
